### ISSUE TITLE
Implement matching based on labels

### ISSUE THREAD

**Issue by benceszikora** [bloomberg/powerfulseal#174]
We have labels describing different roles for our nodes in the cluster, something like:
```
example.com/local_pv_type=hdd
```

It would be very useful to be able to "match" nodes using these labels. Currently the "groups" property can kind of achieve this, but that only takes into account the values of the labels, not the keys. So if we would have another node with these labels:
```
example.com/local_pv_type=ssd
example.com/host_disk_type=hdd
```
It would get matched, even though our intention would be to only match that value for a specific key.

I would envisage this working very similarly to the pod selector, so something like this:
```
nodeScenarios:
  - name: "kill hdd nodes"
    match:
      - labels:
          selector: "example.com/local_pv_type=hdd"
```

I would be happy to implement this, but I wanted to get some feedback before I get started. @seeker89 do you have any thoughts?
