### ISSUE TITLE
How to kill a specific pod 

### ISSUE THREAD

**Issue by white-cloud** [bloomberg/powerfulseal#194]
**Describe the bug**
Hello , 

I'm using stateful application and in my scenario i need to kill only one pod from my stateful namespace , i don't want to kill all my pods under the same namespace. How can i accomplish that please.

Thank you in advance.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Operating System and Version: [e.g. Ubuntu Linux 18.04]
 - Browser [e.g. Firefox, Safari] (if applicable):

**Additional context**

**Comment by seeker89** [comment]
Hi there!

If you want to kill a random, single pod from a namespace, you can use a config file much like this one:

```yaml
config:
  minSecondsBetweenRuns: 30
  maxSecondsBetweenRuns: 60

nodeScenarios: []
podScenarios:
  - name: "delete random pods in my namespace"

    match:
      - namespace:
          name: "mynamespace"

    filters:
      - randomSample:
          size: 1

    actions:
      - kill:
          probability: 1
          force: true
```

**Comment by white-cloud** [comment]
@seeker89  Thank you for your response, 
I tried a similar config, but unfortunatly it's not what i want for my scenario for exemple i need to kill always pod-0 , i have for example Pod0-Pod1 (i want to kill each 10 min Pod-0). is there a way to do that please.

Thank you again.

**Comment by seeker89** [comment]
You can mark the pod you want to target with a label of your choice and then do something like this:

```yaml
      - labels:
          namespace: "mynamespace"
          selector: "mylabel=myvalue"
```

**Comment by rkgithubp** [comment]
what is "size" in randomSample? if set to 2, will it kill 2 pods randomly at a time?
      - randomSample:
          size: 1

**Comment by white-cloud** [comment]
Hello @seeker89 

Thank you for your answer, that works for me.
I want to ask if it is possible to specify the percentage of failure for example if i want to have 10% of failures , is there any way to specify that , could it be the   **probability: 1** parameter ?

Thank you.

**Comment by seeker89** [comment]
@rkgithubp yes, `randomSample->size` takes a random sample of the specified size (integer).

@white-cloud that would depend on what you mean by `10% of failures`.

If you want to take 10% of the pods that have your label applied, you can do:

```yaml
    filters:
      - randomSample:
          ratio: 0.1
```

If, on the other hand, you want to select them all, and only kill them 10% of the time on average, then you can skip filters, and add `probability: 0.1` to your kill action.
