### ISSUE TITLE
[Experimental] Powerfulseal-agent

### ISSUE THREAD

**Issue by dgzlopes** [bloomberg/powerfulseal#202]
This work is based on #136 and #120 discussions.

I decided to build a **proof of concept** around this feature, and [Powerfulseal-agent](https://github.com/dgzlopes/powerfulseal-agent) is the result.

Long history short. Powerfulseal-agent is a container packed with deadly tools (`stress`, `tc`, `sysrq access`). These tools are used by Attacks. These Attacks can be Listed, Deleted or Created with API calls. When creating a new attack you can customize it with a set of args.

Examples of Attacks? Right now CPU, Memory, Shutdown, and Restart attacks work.

More docs available [here](https://github.com/dgzlopes/powerfulseal-agent).

Cool things:
- One container. Deployed [on-demand](https://github.com/bloomberg/powerfulseal) or as a [daemonset](https://github.com/bloomberg/powerfulseal).
- Easy to add new attack types.
- Easy to add new attack surfaces.
- REST API. It can be deployed/used by other projects too.
- Small codebase.
- Minimal setup.
- Integration with Powerfulseal should be easy.
- Works :)

Ugly things:
- Some parts of the code
- No requirements.txt.
- No packaging.
- No CD/CI.
- No docs.
- No tests.
- No retry errors in the API.
- Container size.
- (A lot of things)

I would love to hear your thoughts on this. I'm happy to answer any questions :)

**Comment by dgzlopes** [comment]
As a note. Right now this lives in its own repo, but if its the right direction... I'm happy to move the dev work to the main repo :)

**Comment by seeker89** [comment]
I love the idea! Added to my todo list to give your repo a try!

**Comment by seeker89** [comment]
Hey, sorry for being slow at getting to this. Crazy times we live in.

**Comment by dgzlopes** [comment]
I'm still interested in working on a production-ready version of this (almost complete rewrite, this was a POC :P)- if needed I can create some spec/formal description.

Did you have some time to give it a look? I feel this addition pairs well with the sidecar-model proposed for Network disruptions/attacks - and would like to remove the attack abstractions to further rely on the base tools (stress-ng... etc).

Actually this model is similar to the one that Service-mesh implements:
![Screenshot from 2020-08-19 11-10-46](https://user-images.githubusercontent.com/8228060/90615644-b1481e80-e20c-11ea-8961-e9fd3a05fbf1.png)
(with one daemon and multiple sidecars)

**Comment by dgzlopes** [comment]
Nice, happy to see that we go forward with this idea :) 

I'll allocate some time this week to write a more formal/concise proposal that hopefully can address the points that you cited.

Then, we can start ironing/discussing the details :blush:

(btw, your book looks awesome :rocket: )

**Comment by simskij** [comment]
As per our discussion, @dgzlopes, I think it would make sense to also check out whether it would be sufficient to do this with ConfigMaps and jobs, allowing us to stick to k8s primitives rather than having to build a lot of custom tooling. As you mentioned,  this kind of depends on whether jobs allow usage of `nodeSelector`s or not.

Below are some examples I put together as part of a PoC I did for k6:

k6.job.yml
```yaml
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: k6-1
        jobgroup: k6-performance-test
    spec:
      containers:
      - command:
        - k6
        - run
        - /test/test.js
        env:
        - name: K6_NODES_TOTAL
          value: "5"
        - name: K6_NODES_INDEX
          value: "1" // Likely not needed for this, I used this to be able to split load between instances of the job
        - name: K6_TEST_ID
          value: aaaabbbb
        image: loadimpact/k6:new-executors
        imagePullPolicy: IfNotPresent
        name: k6
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /test
          name: test-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: k6-test
        name: test-volume
```

k6.configmap.yml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test
  namespace: default
data:
  test.js: |
    import http from 'k6/http';

    import { Rate } from 'k6/metrics';
    import { check, sleep } from 'k6';

    const failRate = new Rate('failed_requests');

    function getExecutionSegment() {
      const n = __ENV.K6_NODES_INDEX;
      const s = __ENV.K6_NODES_TOTAL;

      let sequence = [];
      for (let i=0; i <= s; i++) {
        sequence.push(`${i}/${s}`);
      }

      let output = {
        executionSegment: `${n-1}/${s}:${n}/${s}`,
        executionSegmentSequence: sequence.join(','),
      }

      console.log(JSON.stringify(output, null, 2));
      return output;
    }


    const segment = getExecutionSegment();
    export const options = {
      executionSegment: segment.executionSegment,
      executionSegmentSequence: segment.executionSegmentSequence,
      stages: [
            { target: 200, duration: '30s' },
            { target: 0, duration: '30s' },
      ],
      threshold: {
        failed_requests: ['rate<=0'],
        http_req_duration: ['p(95)<500'],
      },
    };

    export default function () {
      console.log(__VU);
      const result = http.get('https://test-api.k6.io/public/crocodiles/');
      check(result, {
        'http response status code is 200': result.status === 200,
      });
      failRate.add(result.status !== 200);
      sleep(1);
    }
```

**Comment by dgzlopes** [comment]
So yeah, had a small (but productive) talk with @simskij  about this feature and he helped me rethink some concepts/approaches used on the Powerfulseal-agent POC.

We thought that maybe it's a good idea to use Kubernetes primitives for building this feature instead of building API's and fiddling with security.

How? Using Kubernetes Jobs and NodeSelectors.

Some benefits:
- Remove the need for an API.
- Fewer security issues - see 1.
- No pull and no push - we can use Kubernetes!
- Works if Powerfulseal runs inside or outside the cluster.  
- People can use their Chaos tools inside K8s (if they want).
- We can fully manage the lifecycle with Powerfulseal.
- We can integrate this as an extra action.
- Easier to develop and maintain.


The idea is that you have some kind of Node action:

```
- nodeAction:
  # pick all master VMs
  matches:
    - property:
        name: "name"
        value: ".*master.*"
  filters:
    # only pick the VMs which are in UP state
    - property:
        name: "state"
        value: "UP"
    # and only pick a single VM
    - randomSample:
        size: 1
  actions:
    - job:
        # maybe we can have a default image with some tools - (?)
        image: powerfulseal_job
        cmd: stress-ng --cpu 4
        duration: 60s
	
```


And well, schedule jobs with certain commands/actions/stuff, to create Chaos on your nodes. Also, this would help power users that want to run their tools or craft complex attacks with the existing tools.

This approach would work too if we want to abstract that complexity from the users! We could build a thin layer on top of this with predefined CPU, MEMORY, stuff - attacks :)

Lifecycle? Powerfulseal can deploy these jobs on-demand, and collect the hanging ones when it finishes, or something happens.

To be fair, I prefer this approach - It's more flexible, easier to maintain/develop, and as powerful (or more!!) as my initial POC.


But... It's just another POV - we can dig further on this approach or follow the initial one @seeker89, I suppose there is no silver bullet!

(btw, @simskij helped a lot on this proposal. Thanks a lot!)
