### ISSUE TITLE
Extend the Policies to support initial setup with before and after

### ISSUE THREAD

**Issue by seeker89** [bloomberg/powerfulseal#222]
Currently, PowerfulSeal only modifies the existing state. That means, that in order to introduce a test element (let's say a new deployment in order to verify something on it), you need to add extra software.

I'd like PowerfulSeal to support that out of the box. My proposal is to add two new supported fields, similar to what unit tests framework offer: `before` and `after`.

For example:

```yaml
...
podScenarios:

- name: Some verification

  # this will be executed before the whole scenario
  before:
  - name: create some new pods we're going to test on
    # does an equivalent of `kubectl apply -f`
    apply: /some/path/to/manifests.yaml
  - name: make sure we only have two pods in this deployment
    scale:
      deployment: canary-a
      namespace: test-namespace
      replicas: 2
  - name: verify the pods are there
    verify:
      retries: 3
      delay: 1000ms
      http:
        service: some-service
        namespace: some-namespace
        code: 200
        timeout: 100ms

  # this will be executed after the whole scenario - for example to do some cleanup
  after:
  - name: create some new pods we're going to test on
    # does an equivalent of `kubectl delete -f`
    delete: /some/path/to/manifests.yaml


```
