### ISSUE TITLE
Add verification action to the policies

### ISSUE THREAD

**Issue by seeker89** [bloomberg/powerfulseal#224]
Currently, PowerfulSeal is leaving the verification out for other tools to handle. We'd like to add some low-hanging fruit to the system to allow for verifying things. A lot of people asked about and/or requested this behaviour, for example https://github.com/bloomberg/powerfulseal/issues/203

In particular, I suggest adding the new field `verify` to the Seal. It could be used in `before`, `after` and `action` fields.

Here's a few examples of what I'd like to support in the first version of that: `http` and `pod` probes.

```yaml

# these generic settings can be added to any verify statement
  - name: verify the pods are there
    verify:
      retries: 3
      delay: 1000ms

...

  # verify can go into a before section
  before:
  - name: verify the service responds OK
    verify:
      http:
        # make a hundred requests to guarantee we hit every pod in the service
        count: 100
        target:
          # pick the service or ingress
          service: some-service
          # ingress: some-ingress
          namespace: some-namespace
        endpoint: /healthz
        code: 200
        timeout: 100ms

 # assuming that we are in action section,
 # we can check every pod that is a result of matching and filtering as an action
  - name: do something with pods
    match: [...] 
    filters: [...]
    actions:
    - name: verify the pod responds OK
      verify:
        http:
          endpoint: /healthz
          code: 200
          timeout: 100ms

 # we can also check the status of each pod
  - name: do something else with pods
    match: [...] 
    filters: [...]
    actions:
    - name: verify all pods are running
      verify:
        pod:
          status: "Running"
          #status: "CrashLoopBackOff"

```
