### ISSUE TITLE
Docs improvements - part 2

### ISSUE THREAD

**Issue by seeker89** [bloomberg/powerfulseal#240]
Ideas:

- add logo to the welcome page
- revamp getting started
  - add info about virtualenv
  - show example command to start seal pointing to a kubectl in interactive mode
  - show example command with a basic policy file killing random pods from all namespaces
- revamp setup
  - cleanup the arguments which are no longer needed
  - remove unnecessary arguments from the minikube examples 
  - make it easy to understand that you can run with a cloud driver or without
- metrics - give them a separate section

**Comment by dgzlopes** [comment]
Some more ideas:
- add some kind of architecture/concepts/terminology section
- integrate docs-schema
- detail how to extend powerfulseal (metric, cloud, filters)
- replace interactive mode gifs with Asciinema recordings (easier to stop/read)
- explain when/why you should use each mode
- add real-world policy examples

**Comment by jcstanaway** [comment]
Here's a simple pod scenario we're using.  Note the use of both `filter.randomSample.ratio` and `filter.randomSample.size`. This is to account for any "co-chaos" caused by faults, evictions, node failures, upgrades, etc that happen to occur at the same time the scenario is executed.  If seal came along and also killed pods, then that could reduce the number of pods down below an acceptable level (can't met availability, performance or other SLAs).

In this specific deployment, there are normally only 2 replicas.  `ratio` would be adjusted based on the normal number of replicas running and the minimum required.  Therefore, in this scenario, if there was only one replica running, seal will not attempt to kill it.

`size` is also set to account for any pod auto-scaling that might occur to ensure that the use of `ratio` doesn't attempt to kill more pods than desired.

```
- name: "kill a single healthcheck pod"
  match:
    - deployment:
        namespace: mynamespace
        name: healthcheck
  filters:
    - property:
        name: state
        value: "Running"
    - randomSample:
        # ratio = (numReplicasDesired=2 - minReplicasRequired=1) / numReplicasDesired=1
        ratio: 0.5
    - randomSample:
        # Ensure that randomSample.ratio doesn't result in more than one pod selected.
        size: 1
  actions:
    - kill:
        probability: 0.75
        force: true
```
