### ISSUE TITLE
Match Regex Namespaces for pod scenarios

### ISSUE THREAD

**Issue by paigerube14** [bloomberg/powerfulseal#274]
I would like to be able to match/find all pods in a namespace containing a certain regex string. I think adding in regex namespace comparison would more align with the filters section 

Currently you can match on all namespaces 
```
match:
      - namespace:
          name: "*"
```

Would like to add matching based on regex namespaces
```
match:
      - namespace:
          name: "regex-*"
```

Similar to 
```
filters:
      - property:
          name: "name"
          value: "regex-*"
```
