### ISSUE TITLE
Error: Openshift

### ISSUE THREAD

**Issue by forexpiphunter** [bloomberg/powerfulseal#72]
I'm getting an error message when running this command bellow: I'm using Openshift which shouldn't really matter. 

powerfulseal --run-policy-file example.policy --kube-config ~/.kube/config --inventory-kubernetes --no-cloud -v

ERROR:powerfulseal.clouddrivers.no_cloud_driver:Trying to sync things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
Executing '['sh', '-c', 'sudo docker kill -s SIGKILL bb549a611670cc65322bacb4b674c11f0dd9e5c69732e13c93999d4860093206']' on local-10.0.2.15
Pod killed - namespace: metrics - name: alertmanager-metrics-0
Executing '['sh', '-c', 'sudo docker kill -s SIGKILL 6dd2bb3613fbf805ac3ae1e0775c341b500c7458f88319282ae7cced1cd06875']' on local-10.0.2.15
Pod killed - namespace: metrics - name: kube-state-metrics-6b67c7b958-6ccr2
Executing '['sh', '-c', 'sudo docker kill -s SIGKILL cb569d3e3f12c80fc7ad8d25ac97b80244a893d9dd029b7be73eadfb4d778233']' on local-10.0.2.15
Pod killed - namespace: metrics - name: node-exporter-stg5k
Executing '['sh', '-c', 'sudo docker kill -s SIGKILL 39798cab85e96f30af3f4c79bf83bb2c7591650b8e5eba354feb4f984eec704a']' on local-10.0.2.15
Pod killed - namespace: metrics - name: kubernetes-pod-chaos-monkey-b9879fb44-jw4mg
Executing '['sh', '-c', 'sudo docker kill -s SIGKILL 2ad332b2cae785608ed24d8a0bbc5b34240366b60091126ce2e0600bf1dc0564']' on local-10.0.2.15

My Policy is very simple:

```
podScenarios:
 - name: "delete random pods"

   match:
     - namespace:
         name: "metrics"
   filters:
     - property:
         name: "state"
         value: "Running"
   actions:
     - kill:
         probability: 1
         force: true
     - wait:
         seconds: 5
```
